PATCH http://localhost:3000/api/events/6671f04e62ba2c84661b6a15/request-to-join
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNAZ21haWwuY29tIiwiaWQiOiI2NjcxZDRmMjkxYjg2MDNhNDU5MzgxMGQiLCJpYXQiOjE3MTg3NDMxNjF9.PmTpKFOqZdU5qIsREYnI5sHbpa3twcWeZAcuZ_MBN2c